version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: gestor_de_projeto_db
    environment:
      POSTGRES_DB: gestorDeProjeto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Define um volume para persistência dos dados
